### PR TITLE
Fix Lexer errorHandling when there is no tokens

### PR DESCRIPTION
**Pull request by romainneutron**
I encounter an issue when no tokens exist. An error `Undefined offset -1` is triggered.

### CODE REVIEW

**Comment by nikic** [comment]
Under which circumstances do you see the notice? Is it an empty file on HHVM perchance? The change makes sense in any case, just wondering how to reproduce.

**Comment by romainneutron** [comment]
I don't reproduce the issue anymore. However, I remember it was using symfony php 7.0 polyfill with PHP 5.5. This [part of the code of the polyfill](https://github.com/symfony/polyfill-php70/blob/master/Php70.php#L59) triggered an error, leading to `Lexer::errorMayHaveOccurred` returning `true`.

**Comment by romainneutron** [comment]
Does it help you?

**Comment by nikic** [comment]
Merged as https://github.com/nikic/PHP-Parser/commit/c28b8556f512cbcbcdcefa48abc8020751f997cd into 3.x. Thanks :)

**Pull request closed without merging**
