### PR TITLE
Including startFilePos and endFilePos in NodeDumper and Lexer

### PR DESCRIPTION
**Pull request by leilaes**

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Jsut curious, what did you need this for?

**Comment by leilaes** [comment]
Hey, I want to use the offset for generating SSA in https://github.com/ircmaxell/php-cfg which uses your library :) sorry for my mistake in creating a PR

**Comment by TomasVotruba** [comment]
No troubles :) What do you you use PHP CFG for? Maybe Rector/PHPStan can help you better

**Comment by leilaes** [comment]
I want to see the offset in the generated SSA by php-cfg. Then, I want to find all the references to a variable including their offsets. Thank you for the suggested repo, I will have a look :)

**Comment by TomasVotruba** [comment]
> Then, I want to find all the references to a variable including their offsets.

And then? :)

> Thank you for the suggested repo, I will have a look :)

:+1:

**Comment by leilaes** [comment]
Then, I will check if all the references to a variables have been sent to a specific function as part of a bigger project :)

**Comment by TomasVotruba** [comment]
What's the goal of all this?

**Comment by leilaes** [comment]
I’m working on CLQL for https://www.codelingo.io/ which is basically a language for querying AST. But we’re trying to add SSA (and call graph). Basically as soon as I can generate JSON from PHP code in the below format we’ll be able to plug it in to our system and make SSA queryable:
php source:

```
<?php
$a = "a";
$b = $a;
```

json output:

```
{"to":{"filename":"example.php","start_offset":16,"end_offset":17},"from":{"filename":"example.php","start_offset":6,"end_offset":7}}
```
Although I’m slightly new, so I’m not totally sure how our system works yet.
The system is currently closed source, but we really want to open it up in the 6-12 month time frame.

**Comment by TomasVotruba** [comment]
I see, so it's basically diff in AST in JSON. 

Let me know when it's ready :+1: 

Looking briefly at the documentation, apart Rector (PHP), you might also like [ClangMR](https://www.youtube.com/watch?v=ZpvvmvITOrk) (basically Rector for C made by Google). The syntax for refactoring recipes looks very similar.

**Comment by leilaes** [comment]
Thank you very much for suggesting ClangMR :) Sure, I will let you know when we make all the required changes and CLQL for the above purpose is implemented.

**Pull request closed without merging**
