### PR TITLE
Fix deprecated Optional parameter before required parameter on PrintableNewAnonClassNode

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes https://github.com/nikic/PHP-Parser/issues/986

### CODE REVIEW

**Comment by samsonasik** [comment]
Ready to merge 👍

**Comment by staabm** [comment]
Would this error be detected by a php lint CI job? 

If so, would be great to add such github actions

**Comment by samsonasik** [comment]
On rector-sec, we use list of classes as preload, and error detected early.

I compared to php-parser v5, it seems `null` default value is not exists, so I think this is solution with remove default null.

**Comment by staabm** [comment]
I don't question your fix. was only thinking about some CI tooling to make sure we can detect such errors in the future earlier

**Comment by nikic** [comment]
I don't see the deprecation warning printed on the PHP 8.2 and PHP 8.3 CI jobs at all -- I wonder why that is. I do see it when running with these versions locally.

**Pull request merged**
