### PR TITLE
[EncapsedStringPart] Add rawValue attribute

### PR DESCRIPTION
**Pull request by TomasVotruba**
- add fromStringParsed() and fromString() methods to EncapsedStringPart to keep raw value
- add EncapsedStringPartTest

Follow up to:

* https://github.com/nikic/PHP-Parser/pull/831
* https://github.com/nikic/PHP-Parser/pull/832
* https://github.com/nikic/PHP-Parser/pull/833

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Ready for review :heavy_check_mark:

**Comment by TomasVotruba** [comment]
What needs to be done here?

**Comment by nikic** [comment]
I've implemented a variation on this (with some additional handling for doc strings) in https://github.com/nikic/PHP-Parser/commit/f5adbb5e3fa57d2ff7b9ea179b88bcd2ced153e0.

**Comment by TomasVotruba** [comment]
Thanks :clap:

**Pull request closed without merging**
