### PR TITLE
Phpunit - show awesome code coverage in console

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Why not just use --coverage-text on travis?

**Comment by ovr** [comment]
@GrahamCampbell 
This will works for all envs

**Comment by GrahamCampbell** [comment]
> This will works for all envs

Yeh, I know. I'm questioning why we actually want that.

**Comment by ovr** [comment]
It's a suggestion, in my opinion "it's rly cool"

**Comment by GrahamCampbell** [comment]
I don't really like it turned on by default, and it's not, for good reason.

**Comment by nikic** [comment]
Agree with @GrahamCampbell, coverage shouldn't be on by default. It would be nice to get travis to send coverage to scrutinizer for some version (5.6 makes most sense probably?)

**Comment by ovr** [comment]
I will close it, and send PR with scrutinizer CI code coverage

**Pull request closed without merging**
