### PR TITLE
[PHP 8.0] Add exception witout variable

### PR DESCRIPTION
**Pull request by TomasVotruba**
Covers https://github.com/php/php-src/pull/5345

RFC: https://wiki.php.net/rfc/non-capturing_catches

### CODE REVIEW

**Comment by nikic** [comment]
Can you please add a pretty-printer test as well, to make sure it doesn't crash?

**Comment by TomasVotruba** [comment]
Good point. I forgot to update printer itself, fixed now :+1:

**Comment by nikic** [comment]
Thanks!

**Comment by TomasVotruba** [comment]
I'd like to add this feature to @rectorphp. Any ETA on releasing next patch version so I can plan it?

**Comment by nikic** [comment]
@TomasVotruba Done: https://github.com/nikic/PHP-Parser/releases/tag/v4.5.0

**Pull request merged**
