### PR TITLE
Fixed branch alias

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by nikic** [comment]
Maybe just drop this?

**Comment by GrahamCampbell** [comment]
The point of the branch alias is to allow people to install dev version of the package, so it's good to keep it. Alternatively you could just name the branches "correctly", which would avoid the need for aliases at all.

**Comment by nikic** [comment]
Can't people just use dev-master?

**Comment by GrahamCampbell** [comment]
No, that's not a version constraint. That's just a hack which gets the master branch, and breaks, for example if the master branch is renamed, or they have another package which depends on `^4.0`, for example.

**Pull request merged**
