### PR TITLE
exposing variadic & attributes args for param builder

### PR DESCRIPTION
**Pull request by SignpostMarv**
I needed to use some variadic params in code generation, so I've added methods & props to expose the remaining arguments on Node\Param

### CODE REVIEW

**Comment by nikic** [comment]
I'm fine with makeVariadic(), but what's the motivation for setAdditionalAttributes()? If we add something like this, it probably should be added for all builders.

**Comment by SignpostMarv** [comment]
it was a case of "if I'm adding this, why not add this other thing?"- if we're not particularly fussed about exposing additionalAttributes, I can force-push it without the additional attributes method?

**Comment by nikic** [comment]
Yeah, I'd prefer that.

**Comment by SignpostMarv** [comment]
done :)

**Comment by nikic** [comment]
Merged as https://github.com/nikic/PHP-Parser/commit/c877c1a64ff7c3dcdcd78ceed292fc4557ed6fd2 into 3.x. Thanks!

**Pull request closed without merging**
