### PR TITLE
[cs] coding style fixes

### PR DESCRIPTION
**Pull request by TomasVotruba**
Since project require PHP 7.0, I've added some old syntax fixes.
Let me know if these changes are ok for you.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
It's ready!

Would you be interested in setting up automated coding standard in Travis?
Something like? https://github.com/nette/coding-standard#travis-setup

If so, are you ok with classic PSR-2 or do you have some exceptions/extra requirements?

**Comment by nikic** [comment]
> Would you be interested in setting up automated coding standard in Travis?

Nope, don't care about CS enough for that.

**Comment by TomasVotruba** [comment]
> Nope, don't care about CS enough for that.

Sure

**Comment by TomasVotruba** [comment]
Thanks! :clap:

**Pull request merged**
