### PR TITLE
Fix PhpParser\PrettyPrinter\Standard::pStmt_Function()

### PR DESCRIPTION
**Pull request by WinterSilence**
Same to `PhpParser\PrettyPrinter\Standard::pStmt_ClassMethod()` method

### CODE REVIEW

**Comment by nikic** [comment]
Would be nice to add a pretty printer test for this.

**Comment by nikic** [comment]
I also wonder whether we should do this for Expr_Closure as well? Wouldn't expect to hit that in practice, but probably makes sense to keep it consistent.

**Comment by WinterSilence** [comment]
@nikic arrow functions is not short-cut to closure:
> except that using variables from the parent scope is always automatic

**Comment by WinterSilence** [comment]
@nikic that's covered by `pStmt_Function()` tests

**Comment by WinterSilence** [comment]
@nikic 
> I also wonder whether we should do this for Expr_Closure as well?

yes, but it's idea for another PR

**Pull request closed without merging**
