### PR TITLE
add getTraitUses() method to ClassLike

### PR DESCRIPTION
**Pull request by TomasVotruba**
Follow up to #630

Last method missing from all possible clas like stmts

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by TomasVotruba** [comment]
Any ETA to release this small yet code-cleanup feature?

I've added it to Rector to all rules that needed and it works like a charm. 
https://github.com/rectorphp/rector/pull/1932/commits

**Comment by nikic** [comment]
Release published: https://github.com/nikic/PHP-Parser/releases/tag/v4.2.4

**Comment by TomasVotruba** [comment]
Thank you!

**Pull request merged**
