### PR TITLE
fix PrettyPrinter AttributeGroup print error

### PR DESCRIPTION
**Pull request by LinkedDestiny**
Fix PrettyPrinter to make it work in PHP8.0

### CODE REVIEW

**Comment by nikic** [comment]
I'm not sure I understand what this is supposed to fix. This seems like a formatting change?

**Comment by LinkedDestiny** [comment]
> I'm not sure I understand what this is supposed to fix. This seems like a formatting change?

when i use this in PHP8.0, the generated code is invalid like this:

`
Attribute()
public const ENUM_EXAMPLE = 1
`

The '#[]' is not present.

**Comment by LinkedDestiny** [comment]
> I'm not sure I understand what this is supposed to fix. This seems like a formatting change?

image

Here is the main change.

**Comment by nikic** [comment]
Can you please add a test to https://github.com/nikic/PHP-Parser/tree/master/test/code/prettyPrinter?

**Comment by othercorey** [comment]
@LinkedDestiny Do you plan to finish this?

**Comment by nikic** [comment]
Closing this due to inactivity. I don't understand the issue this fixes from the code change, and there is no test case the demonstrates the problem.

**Pull request closed without merging**
